### ISSUE TITLE
status data removed in streams.json

### ISSUE THREAD

**Issue by Dukvah** [iptv-org/iptv-org.github.io#26] opened 2023-05-04 09:41 UTC
### Discussed in https://github.com/orgs/iptv-org/discussions/25

<div type='discussions-op-text'>

<sup>Originally posted by **Dukvah** May  4, 2023</sup>
normally i used to get channel data from [this](https://iptv-org.github.io/api/streams.json) link but today i saw that "status" key has been removed. So I got an error. Is there something I can use as an alternative?

The json file in the link used to look like this:

[
  //...
  {
    "channel": "BBCNews.uk",
    "url": "http://1111296894.rsc.cdn77.org/LS-ATL-54548-6/index.m3u8",
    "http_referrer": "http://example.com/",
    "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
    "status": "online",
    "width": 1280,
    "height": 720,
    "bitrate": 565040,
    "frame_rate": 29.97,
    "added_at": "2022-07-13T04:41:45Z",
    "updated_at": "2022-07-13T04:41:45Z",
    "checked_at": "2022-08-13T14:05:19Z"
  }
  //...
]</div>

**Comment by freearhey** [comment] 2023-05-04 14:38
Duplicate of https://github.com/orgs/iptv-org/discussions/25

**Closed by freearhey** 2023-05-04 14:38 UTC
